### ISSUE TITLE
How do your date types work?

### ISSUE THREAD

**Issue by kylepaulsen** [sagebind/mathpad#4]
I noticed you have custom types for dates. How do I use them? I tried typing `today` and `now` but nothing seems to show up on the right.

Everything else seems to work fine though. Cool extension!

**Comment by sagebind** [comment]
Thanks for the question!

I may not have published the date stuff to the Marketplace yet, I can release a new version sometime today.

**Comment by kylepaulsen** [comment]
Oh ok, no rush or anything. I was just curious. Also not sure if it matters, but it appears you can call mathjs functions like createUnit() . Not sure if this is a security issue or not.

**Comment by sagebind** [comment]
It may be questionable, but as long as arbitrary JS code can't be executed, the risk is minimal. I opened #5 to look into it.

I published the available improvements on `master` as 0.0.2, so if you update the extension in vscode you should be able to play with the new date functions!

**Comment by sagebind** [comment]
Closing now that date support is published; feel free to reopen if you have more questions or concerns!
