### ISSUE TITLE
Is your extension similar to Atom's extension "markdowm-table-calc"?

### ISSUE THREAD

**Issue by gusbemacbe** [sagebind/mathpad#6]
Hello,

I know your extension is in development, but I am curious if your extension is similar to Atom's extension "[markdowm-table-calc](https://atom.io/packages/markdown-table-calc)". His extension is no longer available.

**Comment by sagebind** [comment]
Not quite, that appears to be more of a spreadsheet-like extension that is meant to insert the result of equations directly into the file as text. Mathpad is more of a linear calculator. Mathpad may or may not work for you in the future depending on what you're trying to accomplish.

**Comment by gusbemacbe** [comment]
Thank you for your explanations! I will forward to your beta extension.
